const KeyCode = @import("keycode.zig").KeyCode;
const detectRenderer = @import("../../utils/platform.zig").detectRenderer();

pub fn linuxKeyCodeMapper(code: u32) KeyCode {
    if (detectRenderer == .wayland)
        return switch (code) {
            1 => .Escape,
            14 => .Backspace,
            15 => .Tab,
            28 => .Enter,
            42 => .LeftShift,
            54 => .RightShift,
            29 => .LeftCtrl,
            97 => .RightCtrl,
            56 => .LeftAlt,
            100 => .RightAlt,
            57 => .Space,
            111 => .Delete,
            103 => .Up,
            108 => .Down,
            105 => .Left,
            106 => .Right,
            30 => .A,
            48 => .B,
            46 => .C,
            32 => .D,
            18 => .E,
            33 => .F,
            34 => .G,
            35 => .H,
            23 => .I,
            36 => .J,
            37 => .K,
            38 => .L,
            50 => .M,
            49 => .N,
            24 => .O,
            25 => .P,
            16 => .Q,
            19 => .R,
            31 => .S,
            20 => .T,
            22 => .U,
            47 => .V,
            17 => .W,
            45 => .X,
            21 => .Y,
            44 => .Z,
            59 => .F1,
            60 => .F2,
            61 => .F3,
            62 => .F4,
            63 => .F5,
            64 => .F6,
            65 => .F7,
            66 => .F8,
            67 => .F9,
            68 => .F10,
            87 => .F11,
            88 => .F12,
            else => .Unknown,
        };

    return .Unknown;
}
